### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError

### ISSUE THREAD

**Issue by Destinycjk** [ge-xing/Diff-UNet#40]
我在将项目下载下来，将数据按照要求放入指定路径下后，在默认参数下运行项目，命令指令参考README.md文件，直接python train.py。程序发生报错，报错信息如下：
```
/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.8/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
W1120 14:22:31.912734 139788717360320 torch/distributed/run.py:779] 
W1120 14:22:31.912734 139788717360320 torch/distributed/run.py:779] *****************************************
W1120 14:22:31.912734 139788717360320 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W1120 14:22:31.912734 139788717360320 torch/distributed/run.py:779] *****************************************
usage: train.py [-h] [--local_rank LOCAL_RANK] [--not_call_launch]
train.py: error: unrecognized arguments: --local-rank=1
usage: train.py [-h] [--local_rank LOCAL_RANK] [--not_call_launch]
train.py: error: unrecognized arguments: --local-rank=0
usage: train.py [-h] [--local_rank LOCAL_RANK] [--not_call_launch]
train.py: error: unrecognized arguments: --local-rank=3
usage: train.py [-h] [--local_rank LOCAL_RANK] [--not_call_launch]
train.py: error: unrecognized arguments: --local-rank=2
W1120 14:22:35.787493 139788717360320 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 1617211 closing signal SIGTERM
W1120 14:22:35.788295 139788717360320 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 1617213 closing signal SIGTERM
W1120 14:22:35.788529 139788717360320 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 1617214 closing signal SIGTERM
E1120 14:22:35.827647 139788717360320 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 2) local_rank: 1 (pid: 1617212) of binary: /home/ck/software/anaconda3/envs/DiffUNet/bin/python
Traceback (most recent call last):
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.8/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.8/site-packages/typing_extensions.py", line 2636, in wrapper
    return arg(*args, **kwargs)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.8/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-20_14:22:35
  host      : estar-Super-Server
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 1617212)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
finish
```
我根据这个报错，自己调整环境，改了下代码啥的，都不太work，反而会有其他一些问题。很奇怪，好像大家似乎都没有碰到这样的问题。请问作者在开发过程中，有没有碰到这个问题？非常期待您的回复！

**Comment by ge-xing** [comment]
env = "DDP" # or env = "pytorch" if you only have one gpu.

max_epoch = 300
batch_size = 2
val_every = 10
num_gpus = 4

这里面的参数 env你设置为pytorch，num_gpus设置为1 用单卡跑看看报错

**Comment by Destinycjk** [comment]
谢谢您的回复！单卡跑似乎应该没有问题了，但是报了一个新的问题，如下：
`> collate dict key "foreground_start_coord" out of 5 keys
>> collate/stack a list of numpy arrays
>> collate/stack a list of tensors
> collate dict key "foreground_end_coord" out of 5 keys
>> collate/stack a list of numpy arrays
>> collate/stack a list of tensors
> collate dict key "label" out of 5 keys
>> collate/stack a list of tensors
  0%|                                                                                                                                                                                  | 0/9 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "/home/ck/workspace/Diff-UNet/BTCV/train.py", line 192, in <module>
    trainer.train(train_dataset=train_ds, val_dataset=val_ds)
  File "/home/ck/workspace/Diff-UNet/BTCV/light_training/trainer.py", line 262, in train
    self.train_epoch(
  File "/home/ck/workspace/Diff-UNet/BTCV/light_training/trainer.py", line 361, in train_epoch
    for idx, batch in enumerate(loader):
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/monai/data/utils.py", line 495, in list_data_collate
    ret = collate_meta_tensor(data)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/monai/data/utils.py", line 464, in collate_meta_tensor
    return {k: collate_meta_tensor([d[k] for d in batch]) for k in elem_0}
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/monai/data/utils.py", line 464, in <dictcomp>
    return {k: collate_meta_tensor([d[k] for d in batch]) for k in elem_0}
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/monai/data/utils.py", line 469, in collate_meta_tensor
    return default_collate(batch)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 265, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 171, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 119, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/torch/utils/data/_utils/collate.py", line 162, in collate_tensor_fn
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [1, 90, 512, 512] at entry 0 and [1, 117, 512, 512] at entry 4

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/ck/software/anaconda3/envs/DiffUNet/lib/python3.10/site-packages/monai/data/utils.py", line 508, in list_data_collate
    raise RuntimeError(re_str) from re
RuntimeError: stack expects each tensor to be equal size, but got [1, 90, 512, 512] at entry 0 and [1, 117, 512, 512] at entry 4

MONAI hint: if your transforms intentionally create images of different shapes, creating your `DataLoader` with `collate_fn=pad_list_data_collate` might solve this problem (check its documentation).`
关于这个问题，您是否有遇到过呢？非常期待您的回复！谢谢!

**Comment by Destinycjk** [comment]
问题已解决，将batch size调整为1即可。另外，单显卡训练对于4090来讲可能会爆显存，解决方法是可以调整网络的feature size，我目前的修改为：
![图片](https://github.com/user-attachments/assets/77659699-b7d6-45ac-9df4-deeec1486f41)
可供参考。最后，非常感谢作者的手把手式Debug改代码！！
